version: '3.7'

services:
  mysql_5_6:
    image: mysql:5.6
    container_name: mysql_5_6_container
    # restart: always  # Remove or comment out this line to prevent automatic restart
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork

  couchdb:
    image: couchdb:3.2.1
    container_name: couchdb_container
    ports:
      - "5985:5984"
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: root
    volumes:
      - couchdb_data:/opt/couchdb/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails s -b 0.0.0.0
    environment:
      - BUNDLE_PATH=/bundle
    ports:
      - 3009:3000

volumes:
  mysql_data:
  couchdb_data:

networks:
  mynetwork:
    external: true
